-- MySQL Script generated by MySQL Workbench
-- 04/09/14 23:44:02
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OptiGrade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OptiGrade` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OptiGrade` ;

-- -----------------------------------------------------
-- Table `TipoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoCuenta` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Visibilidad` ENUM('Pública', 'Oculta', 'Privada') NOT NULL DEFAULT 'Pública',
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `TipoCuentaId` INT NOT NULL,
  `Cuota` INT NOT NULL DEFAULT 10,
  `Unidad` ENUM('Hojas','Días') NOT NULL DEFAULT 'Hojas',
  `Visibilidad` ENUM('Pública', 'Oculta', 'Privada') NOT NULL DEFAULT 'Pública',
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Plan_TipoCuenta_idx` (`TipoCuentaId` ASC),
  CONSTRAINT `fk_Plan_TipoCuenta`
    FOREIGN KEY (`TipoCuentaId`)
    REFERENCES `TipoCuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuenta` (
  `Id` INT NOT NULL,
  `TipoCuentaId` INT NOT NULL,
  `PlanId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Saldo` INT NOT NULL DEFAULT 0,
  `Bloqueada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Cuenta_TipoCuenta_idx` (`TipoCuentaId` ASC),
  INDEX `fk_Cuenta_Plan_idx` (`PlanId` ASC),
  CONSTRAINT `fk_Cuenta_TipoCuenta`
    FOREIGN KEY (`TipoCuentaId`)
    REFERENCES `TipoCuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cuenta_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona` (
  `Id` INT NOT NULL,
  `DNI` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `Nombre` VARCHAR(32) NOT NULL,
  `Apellido` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `DNI_DV_UNIQUE` (`DNI` ASC, `DV` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `País`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `País` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Nacionalidad` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Nacionalidad_UNIQUE` (`Nacionalidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estado` (
  `Id` INT NOT NULL,
  `PaísId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Estado_País_idx` (`PaísId` ASC),
  CONSTRAINT `fk_Estado_País`
    FOREIGN KEY (`PaísId`)
    REFERENCES `País` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ciudad` (
  `Id` INT NOT NULL,
  `EstadoId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Ciudad_Estado_idx` (`EstadoId` ASC),
  CONSTRAINT `fk_Ciudad_Estado`
    FOREIGN KEY (`EstadoId`)
    REFERENCES `Estado` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compañia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Compañia` (
  `Id` INT NOT NULL,
  `RUC` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `Nombre` VARCHAR(64) NOT NULL,
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RUC_DV_UNIQUE` (`RUC` ASC, `DV` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Compañia_Ciudad_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_Compañia_Ciudad`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClienteIndividual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClienteIndividual` (
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `NombrePerfil` VARCHAR(64) NULL DEFAULT NULL,
  `CorreoRecuperación` VARCHAR(64) NOT NULL,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CuentaId`),
  UNIQUE INDEX `PersonaId_UNIQUE` (`PersonaId` ASC),
  CONSTRAINT `fk_ClienteIndividual_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteIndividual_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClienteCorporativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClienteCorporativo` (
  `CuentaId` INT NOT NULL,
  `CompañiaId` INT NOT NULL,
  `ContactoAdministrativo` INT NOT NULL,
  `TeléfonoAdministrativo` VARCHAR(24) NOT NULL,
  `CorreoAdministrativo` VARCHAR(64) NOT NULL,
  `ContactoTécnico` INT NOT NULL,
  `TeléfonoTécnico` VARCHAR(24) NOT NULL,
  `CorreoTécnico` VARCHAR(64) NOT NULL,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CuentaId`),
  UNIQUE INDEX `CompañiaId_UNIQUE` (`CompañiaId` ASC),
  INDEX `fk_ClienteCorporativo_Persona1_idx` (`ContactoAdministrativo` ASC),
  INDEX `fk_ClienteCorporativo_Persona2_idx` (`ContactoTécnico` ASC),
  CONSTRAINT `fk_ClienteCorporativo_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Persona1`
    FOREIGN KEY (`ContactoAdministrativo`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Persona2`
    FOREIGN KEY (`ContactoTécnico`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónPersonal` (
  `PersonaId` INT NOT NULL,
  `FechaDeNacimiento` DATE NOT NULL,
  `NacionalidadId` INT NOT NULL,
  `LugarDeNacimientoId` INT NOT NULL,
  `Género` ENUM('Femenino','Masculino','Otro') NOT NULL,
  `EstadoCivil` ENUM('Soltero','Casado','Divorciado','Otro') NOT NULL DEFAULT 'Casado',
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`),
  INDEX `fk_InformaciónPersonal_País_idx` (`NacionalidadId` ASC),
  INDEX `fk_InformaciónPersonal_Ciudad1_idx` (`LugarDeNacimientoId` ASC),
  INDEX `fk_InformaciónPersonal_Ciudad2_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_InformaciónPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_País`
    FOREIGN KEY (`NacionalidadId`)
    REFERENCES `País` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_Ciudad1`
    FOREIGN KEY (`LugarDeNacimientoId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_Ciudad2`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuario` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Contraseña` VARCHAR(32) NOT NULL COMMENT ' /* comment truncated */ /*Código de verificación de la contraseña, no la contraseña propiamente dicha.*/',
  `Categoría` ENUM('Propietario', 'Administrador', 'Usuario') NOT NULL DEFAULT 'Usuario',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  UNIQUE INDEX `CuentaId_Nombre_UNIQUE` (`CuentaId` ASC, `Nombre` ASC),
  INDEX `fk_Usuario_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Usuario_ClienteCorporativo`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteCorporativo` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alumno` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  INDEX `fk_Alumno_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Alumno_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alumno_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Curso` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `Turno` VARCHAR(8) NOT NULL,
  `Sección` VARCHAR(8) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_Turno_Nombre_Sección_UNIQUE` (`CuentaId` ASC, `Turno` ASC, `Nombre` ASC, `Sección` ASC),
  CONSTRAINT `fk_Curso_ClienteCorporativo`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteCorporativo` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escala` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Escala_Cuenta_idx` (`CuentaId` ASC),
  CONSTRAINT `fk_Escala_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Asignatura` (
  `Id` INT NOT NULL,
  `CursoId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Nombre` VARCHAR(128) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CursoId_Nombre_UNIQUE` (`CursoId` ASC, `Nombre` ASC),
  INDEX `fk_Asignatura_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_Asignatura_Curso`
    FOREIGN KEY (`CursoId`)
    REFERENCES `Curso` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Asignatura_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Profesor` (
  `Id` INT NOT NULL,
  `AsignaturaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `AsignaturaId_PersonaId_UNIQUE` (`AsignaturaId` ASC, `PersonaId` ASC),
  INDEX `fk_Profesor_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Profesor_Asignatura`
    FOREIGN KEY (`AsignaturaId`)
    REFERENCES `Asignatura` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Profesor_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Calificación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Calificación` (
  `Id` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Desde` DECIMAL NOT NULL,
  `Hasta` DECIMAL NOT NULL,
  `Nota` VARCHAR(16) NOT NULL,
  `Letra` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `EscalaId_Nota_UNIQUE` (`EscalaId` ASC, `Nota` ASC),
  UNIQUE INDEX `EscalaId_Letra_UNIQUE` (`EscalaId` ASC, `Letra` ASC),
  CONSTRAINT `fk_Calificación_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActaInstitución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActaInstitución` (
  `Id` INT NOT NULL,
  `AsignaturaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `DataApertura` TIMESTAMP NOT NULL,
  `DataCierre` TIMESTAMP NOT NULL,
  `DataRevisión` TIMESTAMP NOT NULL,
  `Cerrada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ActaInstitución_Asignatura_idx` (`AsignaturaId` ASC),
  INDEX `fk_ActaInstitución_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_ActaInstitución_Asignatura`
    FOREIGN KEY (`AsignaturaId`)
    REFERENCES `Asignatura` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ActaInstitución_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examinador` (
  `ActaId` INT NOT NULL,
  `ProfesorId` INT NOT NULL,
  `Rol` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ActaId`, `ProfesorId`),
  INDEX `fk_Examinador_Profesor_idx` (`ProfesorId` ASC),
  CONSTRAINT `fk_Examinador_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Examinador_Profesor`
    FOREIGN KEY (`ProfesorId`)
    REFERENCES `Profesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaInstitución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaInstitución` (
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `CalificaciónId` INT NOT NULL,
  PRIMARY KEY (`ActaId`, `AlumnoId`),
  INDEX `fk_NotaInstitución_Alumno_idx` (`AlumnoId` ASC),
  INDEX `fk_NotaInstitución_Calificación_idx` (`CalificaciónId` ASC),
  CONSTRAINT `fk_NotaInstitución_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaInstitución_Alumno`
    FOREIGN KEY (`AlumnoId`)
    REFERENCES `Alumno` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaInstitución_Calificación`
    FOREIGN KEY (`CalificaciónId`)
    REFERENCES `Calificación` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Materia` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Nombre` VARCHAR(128) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_Nombre_UNIQUE` (`CuentaId` ASC, `Nombre` ASC),
  INDEX `fk_Materia_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_Materia_ClienteIndividual`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteIndividual` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Materia_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActaProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActaProfesor` (
  `Id` INT NOT NULL,
  `MateriaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `DataApertura` TIMESTAMP NOT NULL,
  `DataCierre` TIMESTAMP NOT NULL,
  `DataRevisión` TIMESTAMP NOT NULL,
  `Cerrada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ActaProfesor_Materia_idx` (`MateriaId` ASC),
  INDEX `fk_ActaProfesor_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_ActaProfesor_Materia`
    FOREIGN KEY (`MateriaId`)
    REFERENCES `Materia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ActaProfesor_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaProfesor` (
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `CalificaciónId` INT NOT NULL,
  PRIMARY KEY (`ActaId`, `AlumnoId`),
  INDEX `fk_NotaProfesor_Alumno_idx` (`AlumnoId` ASC),
  INDEX `fk_NotaProfesor_Calificación_idx` (`CalificaciónId` ASC),
  CONSTRAINT `fk_NotaProfesor_ActaProfesor`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaProfesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaProfesor_Alumno`
    FOREIGN KEY (`AlumnoId`)
    REFERENCES `Alumno` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaProfesor_Calificación`
    FOREIGN KEY (`CalificaciónId`)
    REFERENCES `Calificación` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filiación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filiación` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `Rol` SET('Usuario', 'Profesor', 'Alumno') NOT NULL DEFAULT 'Usuario',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  INDEX `fk_Filiación_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Filiación_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Filiación_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaInstituciónRevisión`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaInstituciónRevisión` (
  `DataRevisión` TIMESTAMP NOT NULL,
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `CalificaciónId` INT NOT NULL,
  `Comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`DataRevisión`, `ActaId`, `AlumnoId`),
  INDEX `fk_NotaInstituciónRevisión_NotaInstitución_idx` (`ActaId` ASC, `AlumnoId` ASC),
  INDEX `fk_NotaInstituciónRevisión_Calificación_idx` (`CalificaciónId` ASC),
  CONSTRAINT `fk_NotaInstituciónRevisión_NotaInstitución`
    FOREIGN KEY (`ActaId` , `AlumnoId`)
    REFERENCES `NotaInstitución` (`ActaId` , `AlumnoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaInstituciónRevisión_Calificación`
    FOREIGN KEY (`CalificaciónId`)
    REFERENCES `Calificación` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaProfesorRevisión`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaProfesorRevisión` (
  `DataRevisión` TIMESTAMP NOT NULL,
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `CalificaciónId` INT NOT NULL,
  `Comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`DataRevisión`, `ActaId`, `AlumnoId`),
  INDEX `fk_NotaProfesorRevisión_Calificación_idx` (`CalificaciónId` ASC),
  INDEX `fk_NotaProfesorRevisión_NotaProfesor_idx` (`ActaId` ASC, `AlumnoId` ASC),
  CONSTRAINT `fk_NotaProfesorRevisión_NotaProfesor`
    FOREIGN KEY (`ActaId` , `AlumnoId`)
    REFERENCES `NotaProfesor` (`ActaId` , `AlumnoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaProfesorRevisión_Calificación`
    FOREIGN KEY (`CalificaciónId`)
    REFERENCES `Calificación` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LimitaciónPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LimitaciónPlan` (
  `PlanId` INT NOT NULL,
  `LímiteCursos` INT NULL DEFAULT NULL,
  `LímiteAsignaturas` INT NULL DEFAULT NULL,
  `LímiteAlumnos` INT NULL DEFAULT NULL,
  `LímiteUsuarios` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PlanId`),
  CONSTRAINT `fk_LimitaciónPlan_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PreciosPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PreciosPlan` (
  `PlanId` INT NOT NULL,
  PRIMARY KEY (`PlanId`),
  CONSTRAINT `fk_PreciosPlan_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeléfonoPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeléfonoPersonal` (
  `PersonaId` INT NOT NULL,
  `Número` VARCHAR(24) NOT NULL,
  `Tipo` ENUM('Domicilio','Trabajo','Fax','Móvil') NOT NULL DEFAULT 'Domicilio',
  `Aclaración` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `Número`),
  CONSTRAINT `fk_TeléfonoPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoPersonal` (
  `PersonaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Descripción` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `URI`),
  UNIQUE INDEX `URI_UNIQUE` (`URI` ASC),
  UNIQUE INDEX `PersonaId_Primario_UNIQUE` (`PersonaId` ASC),
  UNIQUE INDEX `PersonaId_Recuperación_UNIQUE` (`PersonaId` ASC),
  CONSTRAINT `fk_CorreoPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebPersonal` (
  `PersonaId` INT NOT NULL,
  `URL` VARCHAR(256) NOT NULL,
  `Descripción` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `URL`),
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC),
  CONSTRAINT `fk_PáginaWeb_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónFinanciera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónFinanciera` (
  `PersonaId` INT NOT NULL,
  `RUC` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `InforCom` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`),
  UNIQUE INDEX `RUC_DV_UNIQUE` (`RUC` ASC, `DV` ASC),
  CONSTRAINT `fk_InformaciónFinanciera_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónLaboral` (
  `PersonaId` INT NOT NULL,
  `Empresa` VARCHAR(64) NOT NULL,
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `Empresa`),
  INDEX `fk_InformaciónLaboral_Ciudad_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_InformaciónLaboral_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónLaboral_Ciudad`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeléfonoCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeléfonoCompañía` (
  `CompañiaId` INT NOT NULL,
  `Número` VARCHAR(24) NOT NULL,
  `Interno` VARCHAR(8) NOT NULL DEFAULT '',
  `Tipo` ENUM('Escritorio','Fax','Móvil') NOT NULL DEFAULT 'Escritorio',
  PRIMARY KEY (`CompañiaId`, `Número`, `Interno`),
  CONSTRAINT `fk_TeléfonoCompañía_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoCompañía` (
  `CompañiaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Dependencia` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`CompañiaId`, `URI`),
  CONSTRAINT `fk_CorreoCompañía_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebCompañía` (
  `Compañia_Id` INT NOT NULL,
  `URL` VARCHAR(256) NOT NULL,
  `Dependencia` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`Compañia_Id`, `URL`),
  CONSTRAINT `fk_WebCompañía_Compañia1`
    FOREIGN KEY (`Compañia_Id`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoCuenta` (
  `CuentaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Primario` TINYINT(1) NOT NULL DEFAULT TRUE,
  `Recuperación` TINYINT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`CuentaId`, `URI`),
  UNIQUE INDEX `CuentaId_Primario_UNIQUE` (`CuentaId` ASC, `Primario` ASC),
  UNIQUE INDEX `CuentaId_Recuperación_UNIQUE` (`CuentaId` ASC, `Recuperación` ASC),
  CONSTRAINT `fk_CorreoCuenta_Cuenta1`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TipoCuenta`
-- -----------------------------------------------------
START TRANSACTION;
USE `OptiGrade`;
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (1, 'Personal', NULL, 'Alternativa individual económica para profesores.');
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (2, 'Corporativa', NULL, 'Alternativa institucional económica para centros educativos.');
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (3, 'Paquetes', NULL, 'Alternativa general para la adquisición de cuota adicional.');

COMMIT;

