-- MySQL Script generated by MySQL Workbench
-- 04/25/14 09:37:39
-- Model: OptiGrade — Data Model    Version: 1.0

-- OptiGrade 3.0 is an on-line service which provides a software as a service (SAAS) platform to process and store in the cloud optically captured data. It provides an on-line optical answer sheet composer/editor, facilities for the remote scoring and evaluation of multi-choice exams, and a framework with analytic tools for surveys data, captured using desktop optical mark recognition (OMR) technology with a Web-based application front-end.
-- 
-- Copyright © 1997‒2014, OptiSoft Ltd. All rights reserved.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES,NO_AUTO_VALUE_ON_ZERO';
SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;

-- -----------------------------------------------------
-- Schema AccountManagement
-- -----------------------------------------------------
-- Account Management Schema for OptiGrade 3.0 (On-line Service)
-- 
-- Naming convention
-- -----------------------
-- 
-- 1. Plural names for tables, use singular aliases for entities or objects.
-- 2. Singular names for columns.
-- 3. No prefixes for table or column names, except for primary and foreign key columns; use singular prefix.
-- 4. Pascal casing (upper camel casing).
-- 
-- Column ordering (sugested)
-- ---------------------------------
-- 
-- 1. Primary key, including multi-field primary keys that include foreign keys.
-- 2. Foreign key.
-- 3. Unique index.
-- 4. User generated data.
-- 5. System generated data (non-boolean, boolean).
-- 6. Timestamps, etc.
-- 7. Reference to uploaded files.
-- 8. Large binary/text blocks
-- 
-- Relation and Index names
-- -------------------------------
-- 
-- Foreign key relation: fk_RefererentTable_ReferencedTable
-- Foreign key index:    fk_RefererentTable_ReferencedTable_idx
-- Unique columns:        FirstColumnName_SecondColumnName_UNIQUE
-- 
CREATE SCHEMA IF NOT EXISTS `OptiGrade` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `OptiGrade` ;

-- -----------------------------------------------------
-- Table `TipoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoCuenta` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Visibilidad` ENUM('Pública', 'Oculta', 'Privada') NOT NULL DEFAULT 'Pública',
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plan` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `TipoCuentaId` INT NOT NULL,
  `Cuota` INT NOT NULL DEFAULT 10,
  `Unidad` ENUM('Hojas','Días') NOT NULL DEFAULT 'Hojas',
  `Visibilidad` ENUM('Pública', 'Oculta', 'Privada') NOT NULL DEFAULT 'Pública',
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Plan_TipoCuenta_idx` (`TipoCuentaId` ASC),
  CONSTRAINT `fk_Plan_TipoCuenta`
    FOREIGN KEY (`TipoCuentaId`)
    REFERENCES `TipoCuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cuenta` (
  `Id` INT NOT NULL,
  `TipoCuentaId` INT NOT NULL,
  `PlanId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Saldo` INT NOT NULL DEFAULT 0,
  `Bloqueada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Cuenta_TipoCuenta_idx` (`TipoCuentaId` ASC),
  INDEX `fk_Cuenta_Plan_idx` (`PlanId` ASC),
  CONSTRAINT `fk_Cuenta_TipoCuenta`
    FOREIGN KEY (`TipoCuentaId`)
    REFERENCES `TipoCuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cuenta_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona` (
  `Id` INT NOT NULL,
  `DNI` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `Nombre` VARCHAR(32) NOT NULL,
  `Apellido` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `DNI_DV_UNIQUE` (`DNI` ASC, `DV` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `País`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `País` (
  `Id` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Nacionalidad` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Nacionalidad_UNIQUE` (`Nacionalidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estado` (
  `Id` INT NOT NULL,
  `PaísId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Estado_País_idx` (`PaísId` ASC),
  CONSTRAINT `fk_Estado_País`
    FOREIGN KEY (`PaísId`)
    REFERENCES `País` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ciudad` (
  `Id` INT NOT NULL,
  `EstadoId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Ciudad_Estado_idx` (`EstadoId` ASC),
  CONSTRAINT `fk_Ciudad_Estado`
    FOREIGN KEY (`EstadoId`)
    REFERENCES `Estado` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compañia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Compañia` (
  `Id` INT NOT NULL,
  `RUC` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `Nombre` VARCHAR(64) NOT NULL,
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RUC_DV_UNIQUE` (`RUC` ASC, `DV` ASC),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Compañia_Ciudad_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_Compañia_Ciudad`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClienteIndividual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClienteIndividual` (
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `NombrePerfil` VARCHAR(64) NULL DEFAULT NULL,
  `CorreoRecuperación` VARCHAR(64) NOT NULL,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CuentaId`),
  UNIQUE INDEX `PersonaId_UNIQUE` (`PersonaId` ASC),
  CONSTRAINT `fk_ClienteIndividual_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteIndividual_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClienteCorporativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClienteCorporativo` (
  `CuentaId` INT NOT NULL,
  `CompañiaId` INT NOT NULL,
  `ContactoAdministrativo` INT NOT NULL,
  `TeléfonoAdministrativo` VARCHAR(24) NOT NULL,
  `CorreoAdministrativo` VARCHAR(64) NOT NULL,
  `ContactoTécnico` INT NOT NULL,
  `TeléfonoTécnico` VARCHAR(24) NOT NULL,
  `CorreoTécnico` VARCHAR(64) NOT NULL,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`CuentaId`),
  UNIQUE INDEX `CompañiaId_UNIQUE` (`CompañiaId` ASC),
  INDEX `fk_ClienteCorporativo_Persona1_idx` (`ContactoAdministrativo` ASC),
  INDEX `fk_ClienteCorporativo_Persona2_idx` (`ContactoTécnico` ASC),
  CONSTRAINT `fk_ClienteCorporativo_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Persona1`
    FOREIGN KEY (`ContactoAdministrativo`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ClienteCorporativo_Persona2`
    FOREIGN KEY (`ContactoTécnico`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónPersonal` (
  `PersonaId` INT NOT NULL,
  `FechaDeNacimiento` DATE NOT NULL,
  `NacionalidadId` INT NOT NULL,
  `LugarDeNacimientoId` INT NOT NULL,
  `Género` ENUM('Femenino','Masculino','Otro') NOT NULL,
  `EstadoCivil` ENUM('Soltero','Casado','Divorciado','Otro') NOT NULL DEFAULT 'Casado',
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`),
  INDEX `fk_InformaciónPersonal_País_idx` (`NacionalidadId` ASC),
  INDEX `fk_InformaciónPersonal_Ciudad1_idx` (`LugarDeNacimientoId` ASC),
  INDEX `fk_InformaciónPersonal_Ciudad2_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_InformaciónPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_País`
    FOREIGN KEY (`NacionalidadId`)
    REFERENCES `País` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_Ciudad1`
    FOREIGN KEY (`LugarDeNacimientoId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónPersonal_Ciudad2`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UsuarioCorporativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UsuarioCorporativo` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Contraseña` VARCHAR(32) NOT NULL COMMENT ' /* comment truncated */ /*Código de verificación de la contraseña, no la contraseña propiamente dicha.*/',
  `Categoría` ENUM('Propietario', 'Administrador', 'Usuario') NOT NULL DEFAULT 'Usuario',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  UNIQUE INDEX `CuentaId_Nombre_UNIQUE` (`CuentaId` ASC, `Nombre` ASC),
  INDEX `fk_UsuarioCorporativo_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_UsuarioCorporativo_ClienteCorporativo`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteCorporativo` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UsuarioCorporativo_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alumno` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  INDEX `fk_Alumno_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Alumno_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Alumno_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escala` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Tipo` ENUM('Directa','Estadística','Percentil','Personalizada') NOT NULL DEFAULT 'Directa',
  `Ajustada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Definición` TINYTEXT NOT NULL DEFAULT 'RAW' COMMENT 'REGEX:[Desde;Hasta;Nota;Letra]+',
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  INDEX `fk_Escala_Cuenta_idx` (`CuentaId` ASC),
  CONSTRAINT `fk_Escala_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Curso` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `Turno` VARCHAR(8) NOT NULL,
  `Sección` VARCHAR(8) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_Turno_Nombre_Sección_UNIQUE` (`CuentaId` ASC, `Turno` ASC, `Nombre` ASC, `Sección` ASC),
  INDEX `fk_Curso_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_Curso_ClienteCorporativo`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteCorporativo` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Curso_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Asignatura` (
  `Id` INT NOT NULL,
  `CursoId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Nombre` VARCHAR(128) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CursoId_Nombre_UNIQUE` (`CursoId` ASC, `Nombre` ASC),
  INDEX `fk_Asignatura_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_Asignatura_Curso`
    FOREIGN KEY (`CursoId`)
    REFERENCES `Curso` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Asignatura_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Profesor` (
  `Id` INT NOT NULL,
  `AsignaturaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `AsignaturaId_PersonaId_UNIQUE` (`AsignaturaId` ASC, `PersonaId` ASC),
  INDEX `fk_Profesor_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Profesor_Asignatura`
    FOREIGN KEY (`AsignaturaId`)
    REFERENCES `Asignatura` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Profesor_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActaInstitución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActaInstitución` (
  `Id` INT NOT NULL,
  `AsignaturaId` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `DataApertura` TIMESTAMP NOT NULL,
  `DataCierre` TIMESTAMP NOT NULL,
  `DataRevisión` TIMESTAMP NOT NULL,
  `Cerrada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ActaInstitución_Asignatura_idx` (`AsignaturaId` ASC),
  CONSTRAINT `fk_ActaInstitución_Asignatura`
    FOREIGN KEY (`AsignaturaId`)
    REFERENCES `Asignatura` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examinador` (
  `ActaId` INT NOT NULL,
  `ProfesorId` INT NOT NULL,
  `Rol` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ActaId`, `ProfesorId`),
  INDEX `fk_Examinador_Profesor_idx` (`ProfesorId` ASC),
  CONSTRAINT `fk_Examinador_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Examinador_Profesor`
    FOREIGN KEY (`ProfesorId`)
    REFERENCES `Profesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaInstitución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaInstitución` (
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `Correctos` INT NOT NULL,
  `Incorrectos` INT NOT NULL,
  `Ignorados` INT NOT NULL,
  `Puntaje` INT NOT NULL,
  `Respuestas` TINYTEXT NOT NULL,
  PRIMARY KEY (`ActaId`, `AlumnoId`),
  CONSTRAINT `fk_NotaInstitución_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Materia` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Nombre` VARCHAR(128) NOT NULL,
  `Descripción` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_Nombre_UNIQUE` (`CuentaId` ASC, `Nombre` ASC),
  INDEX `fk_Materia_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_Materia_ClienteIndividual`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `ClienteIndividual` (`CuentaId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Materia_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ActaProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ActaProfesor` (
  `Id` INT NOT NULL,
  `MateriaId` INT NOT NULL,
  `EscalaId` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `DataApertura` TIMESTAMP NOT NULL,
  `DataCierre` TIMESTAMP NOT NULL,
  `DataRevisión` TIMESTAMP NOT NULL,
  `Cerrada` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ActaProfesor_Materia_idx` (`MateriaId` ASC),
  INDEX `fk_ActaProfesor_Escala_idx` (`EscalaId` ASC),
  CONSTRAINT `fk_ActaProfesor_Materia`
    FOREIGN KEY (`MateriaId`)
    REFERENCES `Materia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ActaProfesor_Escala`
    FOREIGN KEY (`EscalaId`)
    REFERENCES `Escala` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanillaMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanillaMateria` (
  `Id` INT NOT NULL,
  `MateriaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `MateriaId_AlumnoId_UNIQUE` (`MateriaId` ASC, `AlumnoId` ASC),
  INDEX `fk_PlanillaMateria_Alumno_idx` (`AlumnoId` ASC),
  CONSTRAINT `fk_PlanillaMateria_Materia`
    FOREIGN KEY (`MateriaId`)
    REFERENCES `Materia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PlanillaMateria_Alumno`
    FOREIGN KEY (`AlumnoId`)
    REFERENCES `Alumno` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NotaProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NotaProfesor` (
  `ActaId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  `Correctos` INT NOT NULL,
  `Incorrectos` INT NOT NULL,
  `Ignorados` INT NOT NULL,
  `Puntaje` INT NOT NULL,
  `Respuestas` TINYTEXT NOT NULL,
  PRIMARY KEY (`ActaId`, `AlumnoId`),
  INDEX `fk_NotaProfesor_PlanillaMateria_idx` (`AlumnoId` ASC),
  CONSTRAINT `fk_NotaProfesor_ActaProfesor`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaProfesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_NotaProfesor_PlanillaMateria`
    FOREIGN KEY (`AlumnoId`)
    REFERENCES `PlanillaMateria` (`AlumnoId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filiación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filiación` (
  `Id` INT NOT NULL,
  `CuentaId` INT NOT NULL,
  `PersonaId` INT NOT NULL,
  `Rol` SET('Usuario', 'Profesor', 'Alumno') NOT NULL DEFAULT 'Usuario',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CuentaId_PersonaId_UNIQUE` (`CuentaId` ASC, `PersonaId` ASC),
  INDEX `fk_Filiación_Persona_idx` (`PersonaId` ASC),
  CONSTRAINT `fk_Filiación_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Filiación_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LimitaciónPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LimitaciónPlan` (
  `PlanId` INT NOT NULL,
  `LímiteCursos` INT NULL DEFAULT NULL,
  `LímiteAsignaturas` INT NULL DEFAULT NULL,
  `LímiteAlumnos` INT NULL DEFAULT NULL,
  `LímiteUsuarios` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PlanId`),
  CONSTRAINT `fk_LimitaciónPlan_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PreciosPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PreciosPlan` (
  `PlanId` INT NOT NULL,
  PRIMARY KEY (`PlanId`),
  CONSTRAINT `fk_PreciosPlan_Plan`
    FOREIGN KEY (`PlanId`)
    REFERENCES `Plan` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeléfonoPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeléfonoPersonal` (
  `PersonaId` INT NOT NULL,
  `Número` VARCHAR(24) NOT NULL,
  `Tipo` ENUM('Domicilio','Trabajo','Fax','Móvil') NOT NULL DEFAULT 'Domicilio',
  `Aclaración` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `Número`),
  CONSTRAINT `fk_TeléfonoPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoPersonal` (
  `PersonaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Descripción` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `URI`),
  UNIQUE INDEX `URI_UNIQUE` (`URI` ASC),
  UNIQUE INDEX `PersonaId_Primario_UNIQUE` (`PersonaId` ASC),
  UNIQUE INDEX `PersonaId_Recuperación_UNIQUE` (`PersonaId` ASC),
  CONSTRAINT `fk_CorreoPersonal_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebPersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebPersonal` (
  `PersonaId` INT NOT NULL,
  `URL` VARCHAR(256) NOT NULL,
  `Descripción` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `URL`),
  UNIQUE INDEX `URL_UNIQUE` (`URL` ASC),
  CONSTRAINT `fk_PáginaWeb_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónFinanciera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónFinanciera` (
  `PersonaId` INT NOT NULL,
  `RUC` VARCHAR(16) NOT NULL,
  `DV` VARCHAR(1) NOT NULL DEFAULT '1',
  `InforCom` TINYINT(1) NOT NULL DEFAULT FALSE,
  `Comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`),
  UNIQUE INDEX `RUC_DV_UNIQUE` (`RUC` ASC, `DV` ASC),
  CONSTRAINT `fk_InformaciónFinanciera_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InformaciónLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InformaciónLaboral` (
  `PersonaId` INT NOT NULL,
  `Empresa` VARCHAR(64) NOT NULL,
  `Dirección1` VARCHAR(64) NOT NULL,
  `Dirección2` VARCHAR(64) NULL DEFAULT NULL,
  `ResidenciaId` INT NOT NULL,
  `Detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PersonaId`, `Empresa`),
  INDEX `fk_InformaciónLaboral_Ciudad_idx` (`ResidenciaId` ASC),
  CONSTRAINT `fk_InformaciónLaboral_Persona`
    FOREIGN KEY (`PersonaId`)
    REFERENCES `Persona` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_InformaciónLaboral_Ciudad`
    FOREIGN KEY (`ResidenciaId`)
    REFERENCES `Ciudad` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeléfonoCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeléfonoCompañía` (
  `CompañiaId` INT NOT NULL,
  `Número` VARCHAR(24) NOT NULL,
  `Interno` VARCHAR(8) NOT NULL DEFAULT '',
  `Tipo` ENUM('Escritorio','Fax','Móvil') NOT NULL DEFAULT 'Escritorio',
  PRIMARY KEY (`CompañiaId`, `Número`, `Interno`),
  CONSTRAINT `fk_TeléfonoCompañía_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoCompañía` (
  `CompañiaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Dependencia` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`CompañiaId`, `URI`),
  CONSTRAINT `fk_CorreoCompañía_Compañia`
    FOREIGN KEY (`CompañiaId`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebCompañía`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebCompañía` (
  `Compañia_Id` INT NOT NULL,
  `URL` VARCHAR(256) NOT NULL,
  `Dependencia` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`Compañia_Id`, `URL`),
  CONSTRAINT `fk_WebCompañía_Compañia`
    FOREIGN KEY (`Compañia_Id`)
    REFERENCES `Compañia` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CorreoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CorreoCuenta` (
  `CuentaId` INT NOT NULL,
  `URI` VARCHAR(64) NOT NULL,
  `Primario` TINYINT(1) NOT NULL DEFAULT TRUE,
  `Recuperación` TINYINT(1) NOT NULL DEFAULT FALSE,
  PRIMARY KEY (`CuentaId`, `URI`),
  UNIQUE INDEX `CuentaId_Primario_UNIQUE` (`CuentaId` ASC, `Primario` ASC),
  UNIQUE INDEX `CuentaId_Recuperación_UNIQUE` (`CuentaId` ASC, `Recuperación` ASC),
  CONSTRAINT `fk_CorreoCuenta_Cuenta`
    FOREIGN KEY (`CuentaId`)
    REFERENCES `Cuenta` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscalaCorporativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscalaCorporativo` (
  `ActaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Tipo` ENUM('Directa','Estadística','Percentil','Personalizada') NOT NULL DEFAULT 'Directa',
  `Ajustada` TINYINT(1) NOT NULL DEFAULT 0,
  `Definición` TINYTEXT NOT NULL DEFAULT 'RAW' COMMENT 'REGEX:[Desde;Hasta;Nota;Letra]+',
  PRIMARY KEY (`ActaId`),
  CONSTRAINT `fk_EscalaCorporativo_ActaInstitución_idx`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EscalaIndividual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EscalaIndividual` (
  `ActaId` INT NOT NULL,
  `Nombre` VARCHAR(32) NOT NULL,
  `Tipo` ENUM('Directa','Estadística','Percentil','Personalizada') NOT NULL DEFAULT 'Directa',
  `Ajustada` TINYINT(1) NOT NULL DEFAULT 0,
  `Definición` TINYTEXT NOT NULL DEFAULT 'RAW' COMMENT 'REGEX:[Desde;Hasta;Nota;Letra]+',
  PRIMARY KEY (`ActaId`),
  CONSTRAINT `fk_EscalaIndividual_ActaProfesor_idx`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaProfesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExamenInstitución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExamenInstitución` (
  `ActaId` INT NOT NULL,
  `Tema` VARCHAR(64) NOT NULL,
  `Objetivo` VARCHAR(256) NULL DEFAULT NULL,
  `TipoRespuesta` ENUM('Única','Múltiple') NOT NULL DEFAULT 'Única',
  `NúmeroGrupos` INT NOT NULL DEFAULT 1,
  `NúmeroItems` INT NOT NULL DEFAULT 60,
  `NúmeroTópicos` INT NOT NULL DEFAULT 1,
  `PuntosItem` INT NOT NULL DEFAULT 1,
  `NúmeroPenalizaciónIncorrecto` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónIncorrecto` INT NOT NULL DEFAULT 0,
  `NúmeroPenalizaciónMúltiple` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónMúltiple` INT NOT NULL DEFAULT 0,
  `NúmeroPenalizaciónIgnorado` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónIgnorado` INT NOT NULL DEFAULT 0,
  `Tópicos` TINYTEXT NOT NULL COMMENT 'EREG=(Tópico:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*)((Tópico:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*))*',
  `Evaluación` TINYTEXT NOT NULL COMMENT 'EREG=(Nombre:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*)((Nombre:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*))*',
  `ClaveRespuestas` TINYTEXT NOT NULL COMMENT 'Ejemplo' /* comment truncated */ /*
Respuesta Única: A,A^B+,-,...

Respuesta Múltiple: A,A|B,A^B,A&B,+,-,...

+: válido para todos
-: anulado para todos*/,
  `CriteriosEspeciales` TINYTEXT NULL COMMENT 'Ejemplo' /* comment truncated */ /*
Respuesta Única:
1:P=1|(A=1,B=2),I=-1,M=-2,B=0;...

Respuesta Múltiple:
2:P=1|(A=2,B=2,AB=1)|(A=2,B=2,AB=2)|(A=2,B=2,AB=3)|(A=2,B=2),I=-1,M=0,B=0;...*/,
  PRIMARY KEY (`ActaId`),
  CONSTRAINT `fk_ExamenInstitución_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExamenProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExamenProfesor` (
  `ActaId` INT NOT NULL,
  `Tema` VARCHAR(64) NOT NULL,
  `Objetivo` VARCHAR(256) NULL DEFAULT NULL,
  `TipoRespuesta` ENUM('Única','Múltiple') NOT NULL DEFAULT 'Única',
  `NúmeroGrupos` INT NOT NULL DEFAULT 1,
  `NúmeroItems` INT NOT NULL DEFAULT 60,
  `NúmeroTópicos` INT NOT NULL DEFAULT 1,
  `PuntosItem` INT NOT NULL DEFAULT 1,
  `NúmeroPenalizaciónIncorrecto` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónIncorrecto` INT NOT NULL DEFAULT 0,
  `NúmeroPenalizaciónMúltiple` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónMúltiple` INT NOT NULL DEFAULT 0,
  `NúmeroPenalizaciónIgnorado` INT NOT NULL DEFAULT 1,
  `PuntosPenalizaciónIgnorado` INT NOT NULL DEFAULT 0,
  `Tópicos` TINYTEXT NOT NULL COMMENT 'EREG=(Tópico:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*)((Tópico:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*))*',
  `Evaluación` TINYTEXT NOT NULL COMMENT 'EREG=(Nombre:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*)((Nombre:(Desde-Hasta|Item)(,(Desde-Hasta|Item))*))*',
  `ClaveRespuestas` TINYTEXT NOT NULL COMMENT 'Ejemplo' /* comment truncated */ /*
Respuesta Única: A,A^B+,-,...

Respuesta Múltiple: A,A|B,A^B,A&B,+,-,...

+: válido para todos
-: anulado para todos*/,
  `CriteriosEspeciales` TINYTEXT NULL COMMENT 'Ejemplo' /* comment truncated */ /*
Respuesta Única:
1:P=1|(A=1,B=2),I=-1,M=-2,B=0;...

Respuesta Múltiple:
2:P=1|(A=2,B=2,AB=1)|(A=2,B=2,AB=2)|(A=2,B=2,AB=3)|(A=2,B=2),I=-1,M=0,B=0;...*/,
  PRIMARY KEY (`ActaId`),
  CONSTRAINT `fk_ExamenProfesor_ActaProfesor`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaProfesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinDerechoMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinDerechoMateria` (
  `ActaId` INT NOT NULL,
  `PlanillaId` INT NOT NULL,
  PRIMARY KEY (`ActaId`, `PlanillaId`),
  INDEX `fk_SinDerechoMateria_PlanillaMateria_idx` (`PlanillaId` ASC),
  CONSTRAINT `fk_SinDerechoMateria_ActaProfesor`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaProfesor` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SinDerechoMateria_PlanillaMateria`
    FOREIGN KEY (`PlanillaId`)
    REFERENCES `PlanillaMateria` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlanillaCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlanillaCurso` (
  `Id` INT NOT NULL,
  `CursoId` INT NOT NULL,
  `AlumnoId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CursoId_AlumnoId_UNIQUE` (`CursoId` ASC, `AlumnoId` ASC),
  INDEX `fk_PlanillaCurso_Alumno_idx` (`AlumnoId` ASC),
  CONSTRAINT `fk_PlanillaCurso_Curso`
    FOREIGN KEY (`CursoId`)
    REFERENCES `Curso` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PlanillaCurso_Alumno`
    FOREIGN KEY (`AlumnoId`)
    REFERENCES `Alumno` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinDerechoAsignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinDerechoAsignatura` (
  `AsignaturaId` INT NOT NULL,
  `PlanillaId` INT NOT NULL,
  PRIMARY KEY (`AsignaturaId`, `PlanillaId`),
  INDEX `fk_SinDerechoAsignatura_PlanillaAsignatura_idx` (`PlanillaId` ASC),
  CONSTRAINT `fk_SinDerechoAsignatura_Asignatura`
    FOREIGN KEY (`AsignaturaId`)
    REFERENCES `Asignatura` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SinDerechoAsignatura_PlanillaCurso`
    FOREIGN KEY (`PlanillaId`)
    REFERENCES `PlanillaCurso` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinDerechoExamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinDerechoExamen` (
  `ActaId` INT NOT NULL,
  `PlanillaId` INT NOT NULL,
  PRIMARY KEY (`ActaId`, `PlanillaId`),
  INDEX `fk_SinDerechoExamen_PlanillaCurso_idx` (`PlanillaId` ASC),
  CONSTRAINT `fk_SinDerechoExamen_ActaInstitución`
    FOREIGN KEY (`ActaId`)
    REFERENCES `ActaInstitución` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SinDerechoExamen_PlanillaCurso`
    FOREIGN KEY (`PlanillaId`)
    REFERENCES `PlanillaCurso` (`Id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(48) BINARY NOT NULL,
  `Password` VARCHAR(64) BINARY NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB
COMMENT = 'A set of subjects. A subject is an active entity, generally in the form of a user, process, or device, that causes data to flow among objects or changes the system state. An user is any person who interacts directly with the system.';


-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Roles` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `BaseRoleId` INT NULL DEFAULT NULL,
  `Name` VARCHAR(128) BINARY NOT NULL,
  PRIMARY KEY (`RoleId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `fk_Roles_Roles_idx` (`BaseRoleId` ASC),
  CONSTRAINT `fk_Roles_Roles`
    FOREIGN KEY (`BaseRoleId`)
    REFERENCES `Roles` (`RoleId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Role constraints: a relationship between or among roles. Role hierarchy: a partial order relationship established among roles. A role is a job function wirhin the system that describes the authority and responsability conferred on a user assigned to the role.';


-- -----------------------------------------------------
-- Table `Objects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Objects` (
  `ObjectId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) BINARY NOT NULL,
  PRIMARY KEY (`ObjectId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
COMMENT = 'A set of objects. An object is a passive entity that contains or receive data.';


-- -----------------------------------------------------
-- Table `Operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Operations` (
  `OperationId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) BINARY NOT NULL,
  PRIMARY KEY (`OperationId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
COMMENT = 'A set of actions that may be executed on objects.';


-- -----------------------------------------------------
-- Table `Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Permissions` (
  `PermissionId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(128) BINARY NOT NULL,
  PRIMARY KEY (`PermissionId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
COMMENT = 'A set of descriptions of the type of authorised interactions a subject can have with an object.';


-- -----------------------------------------------------
-- Table `ObjectPermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ObjectPermissions` (
  `ObjectId` INT NOT NULL,
  `PermissionId` INT NOT NULL,
  PRIMARY KEY (`ObjectId`, `PermissionId`),
  INDEX `fk_ObjectPermissions_Permissions_idx` (`PermissionId` ASC),
  CONSTRAINT `fk_ObjectPermissions_Objects`
    FOREIGN KEY (`ObjectId`)
    REFERENCES `Objects` (`ObjectId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ObjectPermissions_Permissions`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `Permissions` (`PermissionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Object/Permission mapping,';


-- -----------------------------------------------------
-- Table `OperationPermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OperationPermissions` (
  `OperationId` INT NOT NULL,
  `PermissionId` INT NOT NULL,
  PRIMARY KEY (`OperationId`, `PermissionId`),
  INDEX `fk_OperationPermissions_Permissions_idx` (`PermissionId` ASC),
  CONSTRAINT `fk_OperationPermissions_Operations`
    FOREIGN KEY (`OperationId`)
    REFERENCES `Operations` (`OperationId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_OperationPermissions_Permissions`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `Permissions` (`PermissionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Operation/Permission mapping.';


-- -----------------------------------------------------
-- Table `RolePermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RolePermissions` (
  `RoleId` INT NOT NULL,
  `PermissionId` INT NOT NULL,
  PRIMARY KEY (`RoleId`, `PermissionId`),
  INDEX `fk_RolePermissions_Permissions_idx` (`PermissionId` ASC),
  CONSTRAINT `fk_RolePermissions_Roles`
    FOREIGN KEY (`RoleId`)
    REFERENCES `Roles` (`RoleId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RolePermissions_Permissions`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `Permissions` (`PermissionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Role permission assignments.';


-- -----------------------------------------------------
-- Table `UserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserRoles` (
  `UserId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `fk_UserRoles_Roles_idx` (`RoleId` ASC),
  CONSTRAINT `fk_UserRoles_Users`
    FOREIGN KEY (`UserId`)
    REFERENCES `Users` (`UserId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserRoles_Roles`
    FOREIGN KEY (`RoleId`)
    REFERENCES `Roles` (`RoleId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'User/Role assignments.';


-- -----------------------------------------------------
-- Table `Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sessions` (
  `SessionId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `Name` VARCHAR(64) NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`SessionId`),
  UNIQUE INDEX `Name_Created_UNIQUE` (`Name` ASC, `Created` ASC),
  INDEX `fk_Sessions_Users_idx` (`UserId` ASC),
  CONSTRAINT `fk_Sessions_Users`
    FOREIGN KEY (`UserId`)
    REFERENCES `Users` (`UserId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'A mapping between a user and an activated subset of the set of roles the user is assigned to.';


-- -----------------------------------------------------
-- Table `SessionRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SessionRoles` (
  `SessionId` INT NOT NULL,
  `RoleId` INT NOT NULL,
  PRIMARY KEY (`SessionId`, `RoleId`),
  INDEX `fk_SessionRoles_Roles_idx` (`RoleId` ASC),
  CONSTRAINT `fk_SessionRoles_Sessions`
    FOREIGN KEY (`SessionId`)
    REFERENCES `Sessions` (`SessionId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SessionRoles_Roles`
    FOREIGN KEY (`RoleId`)
    REFERENCES `Roles` (`RoleId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Role activation constraints. An activated subset of the set of roles a user is assigned to.';

CREATE USER 'Owner' IDENTIFIED BY '12345';
GRANT ALL ON * TO 'Owner';

CREATE USER 'Admin' IDENTIFIED BY '12345';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'Admin';
GRANT EXECUTE ON ROUTINE * TO 'Admin';

CREATE USER 'Operator' IDENTIFIED BY '12345';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'Operator';

CREATE USER 'User' IDENTIFIED BY '12345';
GRANT SELECT, INSERT, TRIGGER ON TABLE * TO 'User';

CREATE USER 'Client' IDENTIFIED BY '12345';
GRANT SELECT ON TABLE * TO 'Client';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TipoCuenta`
-- -----------------------------------------------------
START TRANSACTION;
USE `OptiGrade`;
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (1, 'Personal', NULL, 'Alternativa individual económica para profesores.');
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (2, 'Corporativa', NULL, 'Alternativa institucional económica para centros educativos.');
INSERT INTO `TipoCuenta` (`Id`, `Nombre`, `Visibilidad`, `Descripción`) VALUES (3, 'Paquetes', NULL, 'Alternativa general para la adquisición de cuota adicional.');

COMMIT;

-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server:                       localhost
-- Port:                         3306
-- Server version:               5.6.12-log - MySQL Community Server (GPL)
-- Server OS:                    Windows 7 - 32bit
-- MySQL Workbench version:      6.1.4.11773 Community build 1454
-- HeidiSQL version:             6.0.0.4024
-- phpMyAdmin version:           4.0.4
-- PHP version:                  5.4.16
-- Date/time:                    2014-04-22 17:59:58
-- --------------------------------------------------------
